"""Avatar 情绪规则兼容入口."""

from src.avatar.emotion_rules import (
    AVATAR_COMFORTING,
    AVATAR_CORRECTING,
    AVATAR_DEEP_EXPLAINING,
    AVATAR_EXPLAINING,
    AVATAR_HAPPY,
    AVATAR_IDLE,
    AVATAR_IDLE_TIRED,
    AVATAR_SERIOUS_EXPLAINING,
    AVATAR_STATES,
    CONTEXT_AVATAR_MAP,
    DEFAULT_AVATAR_STATE,
    IDLE_VARIANT_WEIGHTS,
    LEGACY_EMOTION_AVATAR_MAP,
    MESSAGE_TEXT_FIELDS,
    MESSAGE_TOOL_FIELDS,
    RESULT_STATUS_AVATAR_MAP,
    SYSTEM_STATE_AVATAR_MAP,
    TASK_RESULT_FIELDS,
    TEMPORARY_CONTEXT_CATEGORIES,
    TEMPORARY_RESULT_STATES,
    TOOL_AVATAR_MAP,
    TOOL_RESEARCH_STATE_MAP,
    TRANSITION_STATE_MAP,
    USER_CONTEXT_KEYWORDS,
    USER_CONTEXT_PRIORITY,
    get_avatar_fallback_resource_name,
    get_avatar_resource_name,
    load_avatar_config,
    normalize_avatar_state,
    normalize_rule_key,
)

DEFAULT_TASK_STATE = DEFAULT_AVATAR_STATE
DEFAULT_EMOTION_STATE = DEFAULT_AVATAR_STATE
TASK_STATES = AVATAR_STATES
EMOTION_STATES = AVATAR_STATES
TASK_DEFAULT_EMOTION_MAP = SYSTEM_STATE_AVATAR_MAP
TOOL_TASK_MAP = TOOL_AVATAR_MAP
TOOL_EMOTION_MAP = TOOL_AVATAR_MAP
EMOTION_STATE_TASK_MAP = {state: state for state in AVATAR_STATES}
TASK_RESULT_MAP = RESULT_STATUS_AVATAR_MAP
TASK_STATE_ALIASES = {
    **SYSTEM_STATE_AVATAR_MAP,
    **LEGACY_EMOTION_AVATAR_MAP,
    **TOOL_AVATAR_MAP,
}
EMOTION_STATE_ALIASES = TASK_STATE_ALIASES
RESEARCH_EXTENSION_STATES = tuple(set(TOOL_RESEARCH_STATE_MAP.values()))

__all__ = [
    "AVATAR_COMFORTING",
    "AVATAR_CORRECTING",
    "AVATAR_DEEP_EXPLAINING",
    "AVATAR_EXPLAINING",
    "AVATAR_HAPPY",
    "AVATAR_IDLE",
    "AVATAR_IDLE_TIRED",
    "AVATAR_SERIOUS_EXPLAINING",
    "AVATAR_STATES",
    "CONTEXT_AVATAR_MAP",
    "DEFAULT_AVATAR_STATE",
    "DEFAULT_EMOTION_STATE",
    "DEFAULT_TASK_STATE",
    "EMOTION_STATE_ALIASES",
    "EMOTION_STATE_TASK_MAP",
    "EMOTION_STATES",
    "IDLE_VARIANT_WEIGHTS",
    "LEGACY_EMOTION_AVATAR_MAP",
    "MESSAGE_TEXT_FIELDS",
    "MESSAGE_TOOL_FIELDS",
    "RESEARCH_EXTENSION_STATES",
    "RESULT_STATUS_AVATAR_MAP",
    "SYSTEM_STATE_AVATAR_MAP",
    "TASK_RESULT_FIELDS",
    "TASK_DEFAULT_EMOTION_MAP",
    "TASK_RESULT_MAP",
    "TASK_STATE_ALIASES",
    "TASK_STATES",
    "TEMPORARY_CONTEXT_CATEGORIES",
    "TEMPORARY_RESULT_STATES",
    "TOOL_AVATAR_MAP",
    "TOOL_EMOTION_MAP",
    "TOOL_RESEARCH_STATE_MAP",
    "TOOL_TASK_MAP",
    "TRANSITION_STATE_MAP",
    "USER_CONTEXT_KEYWORDS",
    "USER_CONTEXT_PRIORITY",
    "get_avatar_fallback_resource_name",
    "get_avatar_resource_name",
    "load_avatar_config",
    "normalize_avatar_state",
    "normalize_rule_key",
]
